# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# name: Python application

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     env:
#       MY_SECRET   : ${{secrets.commit_secret}}
#       USER_NAME   : githubaction
#       USER_EMAIL  : githubaction@fake.com
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python 3.8
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.8
#     - name: Install dependencies
#       run: |
#         pip3 install --upgrade pip
#         pip3 install beautifulsoup4 markdown
#     - name: Convert markdown to html
#       run: |
#         python3 ./deploy.py
#     - name: Deploy gh-pages
#       run: |
#         if [[ -n $(git status -s) ]]; then
#           git config --local user.name $USER_NAME
#           git config --local user.email $USER_EMAIL
#           git add .
#           git commit -m "deploy to Github pages"
#           git push
#         fi
        
    
